//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Ratcow.Csta.Ecma354 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session", IsNullable=false)]
    public partial class StopApplicationSession {
        
        private string sessionIDField;
        
        private StopApplicationSessionSessionEndReason sessionEndReasonField;
        
        private StopApplicationSessionExtensions extensionsField;
        
        /// <remarks/>
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public StopApplicationSessionSessionEndReason sessionEndReason {
            get {
                return this.sessionEndReasonField;
            }
            set {
                this.sessionEndReasonField = value;
            }
        }
        
        /// <remarks/>
        public StopApplicationSessionExtensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    public partial class StopApplicationSessionSessionEndReason {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("appEndReason", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("definedEndReason", typeof(StopApplicationSessionSessionEndReasonDefinedEndReason))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    public enum StopApplicationSessionSessionEndReasonDefinedEndReason {
        
        /// <remarks/>
        normal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    public partial class StopApplicationSessionExtensions {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session", IsNullable=false)]
    public partial class StopApplicationSessionPosResponse {
        
        private StopApplicationSessionPosResponseExtensions extensionsField;
        
        /// <remarks/>
        public StopApplicationSessionPosResponseExtensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    public partial class StopApplicationSessionPosResponseExtensions {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session", IsNullable=false)]
    public partial class StopApplicationSessionNegResponse {
        
        private StopApplicationSessionNegResponseErrorCode errorCodeField;
        
        private StopApplicationSessionNegResponseExtensions extensionsField;
        
        /// <remarks/>
        public StopApplicationSessionNegResponseErrorCode errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public StopApplicationSessionNegResponseExtensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    public partial class StopApplicationSessionNegResponseErrorCode {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applError", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("definedError", typeof(StopApplicationSessionNegResponseErrorCodeDefinedError))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    public enum StopApplicationSessionNegResponseErrorCodeDefinedError {
        
        /// <remarks/>
        invalidSessionID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ecma-international.org/standards/ecma-354/appl_session")]
    public partial class StopApplicationSessionNegResponseExtensions {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}
